
services:
  envoy:
    image: envoyproxy/envoy:v1.36-latest
    ports:
      - "8000:8000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./plugin.wasm:/etc/envoy/plugin.wasm
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    network_mode: host
    env_file:
      - path: .env

  backend:
    image: ghcr.io/aarnaud/aarnaud/go-httpbin:v2.21.0
    ports:
      - "8081:8080"
